import React, { useEffect, useMemo, useState } from 'react';
import { CalendarDays, Clock, Plus, Save, Trash2, ArrowLeft, BookOpen, Package, Repeat2, UserCheck, UserCog } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { api } from '../services/api';
import { PageWrapper } from '../components/UI/PageWrapper';
import { PageHeader } from '../components/UI/PageHeader';
import { Button } from '../components/UI/Button';
import { useToast } from '../contexts/ToastContext';
import { useUserPreferences } from '../contexts/UserPreferencesContext';

type Day = { dayKey: string; active: boolean; start: string; end: string; breaks: { start: string; end: string }[] };
const DAYS = [{ key: 'monday', label: 'Segunda' }, { key: 'tuesday', label: 'Terça' }, { key: 'wednesday', label: 'Quarta' }, { key: 'thursday', label: 'Quinta' }, { key: 'friday', label: 'Sexta' }, { key: 'saturday', label: 'Sábado' }, { key: 'sunday', label: 'Domingo' }];
const defaults = (): Day[] => DAYS.map(({ key }, i) => ({ dayKey: key, active: i < 5, start: '08:00', end: i === 4 ? '17:00' : '18:00', breaks: [{ start: '12:00', end: '13:00' }] }));
const RECURRENCES = [
  { id: '', label: 'Não repete' },
  { id: 'WEEKLY|1|4', label: 'Semanal — 4 sessões' },
  { id: 'WEEKLY|1|8', label: 'Semanal — 8 sessões' },
  { id: 'WEEKLY|1|12', label: 'Semanal — 12 sessões' },
  { id: 'TWICE_WEEKLY|1|8', label: '2x por semana — 8 sessões' },
  { id: 'TWICE_WEEKLY|1|16', label: '2x por semana — 16 sessões' },
  { id: 'WEEKLY|2|4', label: 'Quinzenal — 4 sessões' },
];

export function AgendaSettings() {
  const navigate = useNavigate(); const { pushToast } = useToast();
  const { preferences, updatePreference } = useUserPreferences();
  const [schedule, setSchedule] = useState<Day[]>(defaults); const [closedDates, setClosedDates] = useState<any[]>([]);
  const [professionals, setProfessionals] = useState<any[]>([]);
  const [date, setDate] = useState(''); const [label, setLabel] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { Promise.all([api.get<any>('/profile/me'), api.get<any[]>('/users')]).then(([data, users]) => { const s = typeof data.schedule === 'string' ? JSON.parse(data.schedule) : data.schedule; const c = typeof data.closed_dates === 'string' ? JSON.parse(data.closed_dates) : data.closed_dates; if (Array.isArray(s)) setSchedule(s.map((d: any) => ({ ...d, breaks: d.breaks || [] }))); if (Array.isArray(c)) setClosedDates(c); setProfessionals((users || []).filter((item: any) => item.role !== 'secretario')); }).catch(() => pushToast('error', 'Não foi possível carregar sua agenda.')); }, []);
  const activeCount = useMemo(() => schedule.filter(d => d.active).length, [schedule]);
  const updateDay = (idx: number, patch: Partial<Day>) => setSchedule(prev => prev.map((d, i) => i === idx ? { ...d, ...patch } : d));
  const save = async () => { setSaving(true); try { await api.put('/profile/me/schedule', { schedule, closed_dates: closedDates }); pushToast('success', 'Minha agenda foi atualizada.'); } catch (e: any) { pushToast('error', e?.message || 'Erro ao salvar agenda.'); } finally { setSaving(false); } };
  return <PageWrapper className="space-y-5 animate-fadeIn"><PageHeader icon={<CalendarDays />} title="Configurações da Agenda" subtitle="Defina seus dias, horários, intervalos, férias e feriados" actions={<div className="flex gap-2"><Button variant="outline" size="sm" iconLeft={<ArrowLeft size={14} />} onClick={() => navigate('/agenda')}>Voltar</Button><Button size="sm" iconLeft={<Save size={14} />} onClick={save} disabled={saving}>{saving ? 'Salvando...' : 'Salvar agenda'}</Button></div>} />
    <div className="grid grid-cols-1 md:grid-cols-3 gap-3"><div className="p-4 bg-white border border-slate-200 rounded-2xl"><p className="text-[10px] uppercase font-black text-slate-400">Dias ativos</p><p className="text-base sm:text-xl font-black text-indigo-600">{activeCount}/7</p></div><div className="p-4 bg-white border border-slate-200 rounded-2xl"><p className="text-[10px] uppercase font-black text-slate-400">Bloqueios</p><p className="text-base sm:text-xl font-black text-rose-500">{closedDates.length}</p></div><div className="p-4 bg-violet-50 border border-violet-100 rounded-2xl text-sm font-semibold text-violet-700">Essas configurações são usadas para organizar sua agenda e disponibilidade.</div></div>
    <section className="bg-white border border-slate-200 rounded-2xl p-5 space-y-5">
      <div><h2 className="font-black text-slate-800">Configurações do agendamento</h2><p className="text-xs text-slate-500 mt-1">Defina como a Agenda abre e quais campos aparecem no novo agendamento.</p></div>
      <div><p className="text-xs font-black uppercase tracking-widest text-slate-600 mb-3">Visualização</p><div className="rounded-2xl border border-slate-100 bg-slate-50 p-4"><p className="text-[11px] text-slate-500 font-semibold mb-3">Modos de visualização disponíveis <span className="text-slate-400">(mínimo 1)</span></p><div className="flex gap-2">{([{ key: 'day', label: 'Dia' }, { key: 'week', label: 'Semana' }, { key: 'month', label: 'Mês' }] as const).map(view => { const enabled = preferences.agenda.enabledViews.includes(view.key); const onlyOne = enabled && preferences.agenda.enabledViews.length === 1; return <button key={view.key} disabled={onlyOne} onClick={() => updatePreference('agenda', { enabledViews: enabled ? preferences.agenda.enabledViews.filter(item => item !== view.key) : [...preferences.agenda.enabledViews, view.key] })} className={`flex-1 py-2.5 rounded-xl text-xs font-black uppercase ${enabled ? 'bg-indigo-600 text-white' : 'bg-white text-slate-400 border border-slate-200'} disabled:opacity-50`}>{view.label}</button>; })}</div></div></div>
      <div><p className="text-xs font-black uppercase tracking-widest text-slate-600 mb-3">Campos no novo agendamento</p><div className="rounded-2xl border border-slate-100 divide-y overflow-hidden">{([{ key: 'showServicesField', title: 'Serviço ou Pacote', desc: 'Mostrar campo de serviço/pacote', icon: <Package size={15} /> }, { key: 'showProfessionalField', title: 'Campo Profissional', desc: 'Mostrar seletor de profissional', icon: <UserCheck size={15} /> }, { key: 'showLivroCaixa', title: 'Lançar no Livro Caixa', desc: 'Mostrar toggle de sincronização financeira', icon: <BookOpen size={15} /> }] as const).map(item => { const active = preferences.agenda[item.key] !== false; return <div key={item.key} className="flex items-center justify-between p-4"><div className="flex items-center gap-3"><span className={active ? 'text-indigo-600' : 'text-slate-400'}>{item.icon}</span><div><p className="text-sm font-bold text-slate-700">{item.title}</p><p className="text-[10px] text-slate-400">{item.desc}</p></div></div><button aria-label={item.title} onClick={() => updatePreference('agenda', { [item.key]: !active })} className={`w-10 h-6 rounded-full p-0.5 ${active ? 'bg-indigo-600' : 'bg-slate-200'}`}><span className={`block bg-white w-5 h-5 rounded-full transition-transform ${active ? 'translate-x-4' : ''}`} /></button></div>; })}</div></div>
      <div><p className="text-xs font-black uppercase tracking-widest text-slate-600 mb-3">Valores padrão</p><div className="rounded-2xl border border-slate-100 divide-y overflow-hidden"><label className="block p-4"><span className="flex items-center gap-2 text-sm font-bold text-slate-700"><UserCog size={15} className="text-slate-400" /> Profissional padrão <small className="ml-auto font-normal text-slate-400">Pré-selecionar ao abrir</small></span><select value={preferences.agenda.defaultProfessionalId || ''} onChange={e => { const selected = professionals.find(item => String(item.id) === e.target.value); updatePreference('agenda', { defaultProfessionalId: e.target.value, defaultProfessionalName: selected?.name || '' }); }} className="mt-2 w-full border rounded-lg px-3 py-2 text-sm"><option value="">Nenhum (não pré-selecionar)</option>{professionals.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="block p-4"><span className="flex items-center gap-2 text-sm font-bold text-slate-700"><Repeat2 size={15} className="text-slate-400" /> Repetição padrão <small className="ml-auto font-normal text-slate-400">Selecionado ao abrir</small></span><select value={preferences.agenda.defaultRecurrence || ''} onChange={e => updatePreference('agenda', { defaultRecurrence: e.target.value })} className="mt-2 w-full border rounded-lg px-3 py-2 text-sm">{RECURRENCES.map(item => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label></div></div>
    </section>
    <section className="bg-white border border-slate-200 rounded-2xl p-5"><h2 className="font-black text-slate-800">Rotina semanal</h2><p className="text-xs text-slate-500 mt-1 mb-4">Ative os dias de atendimento, defina horários e intervalos.</p><div className="space-y-2">{schedule.map((day, idx) => <div key={day.dayKey} className="rounded-xl border border-slate-100 p-3"><div className="flex flex-wrap items-center gap-3"><button onClick={() => updateDay(idx, { active: !day.active })} className={`px-3 py-2 rounded-lg text-xs font-black ${day.active ? 'bg-emerald-500 text-white' : 'bg-slate-100 text-slate-500'}`}>{day.active ? 'Disponível' : 'Fechado'}</button><strong className="text-sm text-slate-700 w-20">{DAYS.find(d => d.key === day.dayKey)?.label}</strong>{day.active && <><input type="time" value={day.start} onChange={e => updateDay(idx, { start: e.target.value })} className="border rounded-lg px-2 py-1.5 text-sm"/><span className="text-slate-400">até</span><input type="time" value={day.end} onChange={e => updateDay(idx, { end: e.target.value })} className="border rounded-lg px-2 py-1.5 text-sm"/><button onClick={() => updateDay(idx, { breaks: [...day.breaks, { start: '12:00', end: '13:00' }] })} className="ml-auto text-xs font-bold text-indigo-600">+ Intervalo</button></>}</div>{day.active && day.breaks.map((b, bi) => <div key={bi} className="ml-24 mt-2 flex items-center gap-2 text-xs text-slate-500"><Clock size={12}/><input type="time" value={b.start} onChange={e => updateDay(idx, { breaks: day.breaks.map((x, i) => i === bi ? { ...x, start: e.target.value } : x) })} className="border rounded px-2 py-1"/> até <input type="time" value={b.end} onChange={e => updateDay(idx, { breaks: day.breaks.map((x, i) => i === bi ? { ...x, end: e.target.value } : x) })} className="border rounded px-2 py-1"/><button onClick={() => updateDay(idx, { breaks: day.breaks.filter((_, i) => i !== bi) })} className="text-rose-500"><Trash2 size={13}/></button></div>)}</div>)}</div></section>
    <section className="bg-white border border-slate-200 rounded-2xl p-5"><h2 className="font-black text-slate-800">Férias, feriados e folgas</h2><div className="mt-4 flex flex-wrap gap-2"><input type="date" value={date} onChange={e => setDate(e.target.value)} className="border rounded-lg px-3 py-2 text-sm"/><input value={label} onChange={e => setLabel(e.target.value)} placeholder="Motivo: férias, feriado..." className="border rounded-lg px-3 py-2 text-sm flex-1 min-w-48"/><Button size="sm" iconLeft={<Plus size={14}/>} onClick={() => { if (!date) return; setClosedDates(prev => [...prev.filter(d => d.date !== date), { date, label: label || 'Folga' }].sort((a,b) => a.date.localeCompare(b.date))); setDate(''); setLabel(''); }}>Bloquear data</Button></div><div className="mt-4 space-y-2">{closedDates.length === 0 ? <p className="text-sm text-slate-400">Nenhuma data bloqueada.</p> : closedDates.map((d: any) => <div key={d.date} className="flex items-center justify-between p-3 bg-rose-50 border border-rose-100 rounded-xl"><span className="text-sm font-bold text-slate-700">{new Date(`${d.date}T12:00:00`).toLocaleDateString('pt-BR')} · {d.label}</span><button onClick={() => setClosedDates(prev => prev.filter(x => x.date !== d.date))} className="text-rose-500"><Trash2 size={15}/></button></div>)}</div></section>
  </PageWrapper>;
}
